version: "3"

networks:
  todoapp-net:

services:
  pythonapp:
    image: todoapp:2.0.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PYTHONUNBUFFERED=1
      - ENGINE=${ENGINE}
      - NAME=${NAME}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOST=${HOST}
      - PORT=${PORT}
    networks:
      - todoapp-net
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql-local:1.0.0
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: my-sql
    ports:
      - "3306:3306"
    volumes:
      - todoapp-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${PASSWORD}
      - MYSQL_DATABASE=${NAME}
      - MYSQL_USER=${USER}
      - MYSQL_PASSWORD=${PASSWORD}
    networks:
      - todoapp-net

volumes:
  todoapp-db-data:
